### PR TITLE
Remove cherry picks that are no longer needed (since they have been merged to main)

### PR DESCRIPTION
**Pull request by sandbergja**

### CODE REVIEW

**Comment by bmagic007** [comment]
Thanks Jane! Though, I think it's time to delete the redis build altogether, and I'll remove the dockerhub image soon.

**Comment by sandbergja** [comment]
Cool!  Makes sense!  Okay if I close this puppy then?

**Comment by bmagic007** [comment]
Sure, or maybe make another commit that removes the folder, and we can merge that. Also: you should be able to do the merging now :)

**Comment by sandbergja** [comment]
Closing, since I didn't get around to removing the folder -- apologies!

**Pull request closed without merging**
